<?php
/** @var \MageSuite\GoogleCustomerReviews\ViewModel\Badge $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isEnabled()) : ?>
    <script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
    <script>
        window.renderBadge = function() {
            var ratingBadgeContainer = document.createElement("div");
            document.body.appendChild(ratingBadgeContainer);
            window.gapi.load('ratingbadge', function() {
                window.gapi.ratingbadge.render(ratingBadgeContainer, <?= /* @noEscape */ $viewModel->getJsonConfig() ?>);
            });
        }
    </script>
<?php endif; ?>
